import type {
  Finding,
  JobResultResponse,
  JobSummary,
  RemediationRecord,
  RemediationSummary,
  ScanSummary,
} from '../types/api'

export const demoFindings: Finding[] = [
  {
    id: 'DEMO-001',
    finding_key: 'DEMOFINDING001',
    title: 'Demo Local CVE Match',
    severity: 'High',
    source: 'cve_feed',
    category: 'vulnerability_intelligence',
    priority_label: 'Fix First',
    priority_score: 82,
    risk_score: 78,
    cve: 'LOCAL-CVE-DEMO-0001',
    cvss_score: 7.5,
    epss_score: 0.72,
    exploit_available: true,
    affected_host: 'demo-linux.local',
    recommended_action: 'Validate affected package evidence and schedule vendor patch review.',
    limitation: 'Demo metadata only. No real target was scanned.',
    remediation_status: 'in_progress',
    remediation_owner: 'security-team',
    remediation_due_date: '2026-06-15',
    remediation_note: 'Reviewing vendor remediation options.',
    asset_criticality: 'medium',
  },
  {
    id: 'DEMO-002',
    finding_key: 'DEMOFINDING002',
    title: 'SMB Service Exposed',
    severity: 'Medium',
    source: 'service_detect',
    category: 'service_exposure',
    priority_label: 'Fix Soon',
    priority_score: 61,
    risk_score: 58,
    affected_host: 'demo-windows.local',
    affected_port: '445',
    recommended_action: 'Restrict SMB exposure to authorised management networks.',
    limitation: 'Demo finding only.',
    remediation_status: 'open',
    asset_criticality: 'medium',
  },
  {
    id: 'DEMO-003',
    finding_key: 'DEMOFINDING003',
    title: 'Missing Content-Security-Policy',
    severity: 'Medium',
    source: 'web_header_audit',
    category: 'web_headers',
    priority_label: 'Monitor',
    priority_score: 44,
    risk_score: 42,
    affected_url: 'https://demo-web.local/',
    recommended_action: 'Review application compatibility and deploy a tested Content-Security-Policy.',
    limitation: 'Demo finding only.',
    remediation_status: 'in_progress',
    remediation_owner: 'app-team',
    remediation_due_date: '2026-06-30',
    remediation_note: 'Policy draft under review.',
  },
  {
    id: 'DEMO-004',
    finding_key: 'DEMOFINDING004',
    title: 'Cookie Missing HttpOnly Flag',
    severity: 'Medium',
    source: 'web_cookie_audit',
    category: 'web_cookies',
    priority_label: 'Fix Soon',
    priority_score: 56,
    risk_score: 49,
    affected_url: 'https://demo-web.local/',
    recommended_action: 'Set HttpOnly on sensitive session cookies after application testing.',
    limitation: 'Demo finding only.',
    remediation_status: 'fixed',
  },
  {
    id: 'DEMO-005',
    finding_key: 'DEMOFINDING005',
    title: 'SSH Service Exposed',
    severity: 'Informational',
    source: 'vuln_intel',
    category: 'service_exposure',
    priority_label: 'Monitor',
    priority_score: 22,
    risk_score: 18,
    affected_host: 'demo-linux.local',
    affected_port: '22',
    recommended_action: 'Confirm SSH is restricted to authorised administration paths.',
    limitation: 'Demo finding only.',
    remediation_status: 'open',
  },
  {
    id: 'DEMO-006',
    finding_key: 'DEMOFINDING006',
    title: 'Demo Outdated Web Component',
    severity: 'High',
    source: 'vuln_intel',
    category: 'vulnerability_intelligence',
    priority_label: 'Fix First',
    priority_score: 76,
    risk_score: 71,
    affected_host: 'demo-web.local',
    recommended_action: 'Validate component version evidence and plan an update.',
    limitation: 'Demo finding only.',
    remediation_status: 'open',
  },
  {
    id: 'DEMO-007',
    finding_key: 'DEMOFINDING007',
    title: 'TLS Certificate Near Expiry',
    severity: 'Medium',
    source: 'tls_audit',
    category: 'tls_certificate',
    priority_label: 'Fix Soon',
    priority_score: 54,
    risk_score: 48,
    affected_host: 'demo-web.local',
    recommended_action: 'Renew certificate before expiry through normal change control.',
    limitation: 'Demo finding only.',
    remediation_status: 'fixed',
  },
  {
    id: 'DEMO-008',
    finding_key: 'DEMOFINDING008',
    title: 'Missing X-Frame-Options Header',
    severity: 'Medium',
    source: 'web_header_audit',
    category: 'web_headers',
    priority_label: 'Fix Soon',
    priority_score: 50,
    risk_score: 41,
    affected_url: 'https://demo-web.local/',
    recommended_action: 'Add a tested frame-ancestors CSP or X-Frame-Options control.',
    limitation: 'Demo finding only.',
    remediation_status: 'fixed',
  },
  {
    id: 'DEMO-009',
    finding_key: 'DEMOFINDING009',
    title: 'Verbose Server Header',
    severity: 'Low',
    source: 'web_header_audit',
    category: 'information_disclosure',
    priority_label: 'Monitor',
    priority_score: 28,
    risk_score: 24,
    affected_url: 'https://demo-web.local/',
    recommended_action: 'Reduce unnecessary version disclosure where operationally practical.',
    limitation: 'Demo finding only.',
    remediation_status: 'accepted_risk',
  },
  {
    id: 'DEMO-010',
    finding_key: 'DEMOFINDING010',
    title: 'Robots.txt Allows Broad Crawling',
    severity: 'Low',
    source: 'web_robots',
    category: 'web_discovery',
    priority_label: 'Monitor',
    priority_score: 24,
    risk_score: 20,
    affected_url: 'https://demo-web.local/robots.txt',
    recommended_action: 'Review robots guidance against intended exposure.',
    limitation: 'Demo finding only.',
    remediation_status: 'open',
  },
  {
    id: 'DEMO-011',
    finding_key: 'DEMOFINDING011',
    title: 'Web Form Missing CSRF-Like Field',
    severity: 'Low',
    source: 'web_form_audit',
    category: 'web_forms',
    priority_label: 'Monitor',
    priority_score: 30,
    risk_score: 26,
    affected_url: 'https://demo-web.local/contact',
    recommended_action: 'Validate whether the form is state-changing and requires CSRF protection.',
    limitation: 'Demo passive indicator only.',
    remediation_status: 'open',
  },
  {
    id: 'DEMO-012',
    finding_key: 'DEMOFINDING012',
    title: 'Demo Asset Inventory Note',
    severity: 'Informational',
    source: 'asset_inventory',
    category: 'asset_context',
    priority_label: 'Informational',
    priority_score: 8,
    risk_score: 6,
    affected_host: '127.0.0.1',
    recommended_action: 'Keep asset ownership and criticality metadata current.',
    limitation: 'Demo informational record only.',
    remediation_status: 'fixed',
  },
]

export const demoJobs: JobSummary[] = [
  {
    job_id: 'demo-job-001',
    scan_id: 'demo-scan-001',
    target: 'demo-web.local',
    status: 'completed',
    created_at: '2026-05-29T09:00:00+00:00',
    started_at: '2026-05-29T09:00:05+00:00',
    completed_at: '2026-05-29T09:01:18+00:00',
    duration_seconds: 73,
    result_path: 'reports\\demo_report.json',
    result_download_url: '/reports/demo-report-json/download',
    html_report_path: 'reports\\demo_report.html',
    html_view_url: '/reports/demo-report-html/view',
    html_download_url: '/reports/demo-report-html/download',
    result_summary: { total_findings: 12, has_fix_first_dashboard: true, has_trend_data: true },
  },
]

export const demoScans: ScanSummary[] = [
  { scan_id: 'demo-scan-001', target: 'demo-web.local', scan_time: '2026-05-29T09:01:18+00:00', findings_count: 12, duration_seconds: 73 },
  { scan_id: 'demo-scan-000', target: 'demo-web.local', scan_time: '2026-05-28T09:01:18+00:00', findings_count: 13, duration_seconds: 69 },
]

export const demoJobResult: JobResultResponse = {
  job_id: 'demo-job-001',
  status: 'completed',
  result: {
    target: 'demo-web.local',
    findings: demoFindings,
    demo_mode: true,
    asset_context: {
      target: 'demo-web.local',
      criticality: 'medium',
      environment: 'demo',
      business_owner: 'Demo Owner',
      tags: ['portfolio', 'sample-data'],
    },
    prioritisation_summary: {
      total_findings: 12,
      fix_first_count: 2,
      fix_soon_count: 4,
      monitor_count: 5,
      informational_count: 1,
      highest_priority_score: 82,
      asset_criticality: 'medium',
    },
    fix_first_dashboard: {
      enabled: true,
      risk_trend_label: 'Improved',
      new_findings_count: 2,
      resolved_findings_count: 3,
      fix_first_new_count: 0,
      fix_first_resolved_count: 1,
      average_priority_delta: -4,
    },
    prioritisation_trends: {
      enabled: true,
      status: 'compared',
      risk_trend_label: 'Improved',
      previous_scan_id: 'demo-scan-000',
      previous_scan_time: '2026-05-28T09:01:18+00:00',
      current_scan_time: '2026-05-29T09:01:18+00:00',
      previous_findings_count: 13,
      current_findings_count: 12,
      new_findings_count: 2,
      resolved_findings_count: 3,
      priority_increased_count: 1,
      priority_decreased_count: 2,
      fix_first_new_count: 0,
      fix_first_resolved_count: 1,
      fix_first_persisting_count: 2,
      average_priority_delta: -4,
      highest_priority_delta: -6,
    },
    prioritisation_trend_details: {
      new_findings: demoFindings.slice(0, 2),
      resolved_findings: demoFindings.slice(2, 5),
      priority_increased: demoFindings.slice(0, 1),
      priority_decreased: demoFindings.slice(1, 3),
      fix_first_new: [],
      fix_first_resolved: demoFindings.slice(0, 1),
      fix_first_persisting: demoFindings.slice(0, 2),
    },
    vulnerability_intelligence: { enabled: true, demo_data: true, matched_findings: 2 },
    web_dast_summary: { enabled: true, demo_data: true, passive_checks: 8 },
  },
}

export const demoRemediationRecords: RemediationRecord[] = [
  { finding_key: 'DEMOFINDING003', title: 'Missing Content-Security-Policy', target: 'demo-web.local', severity: 'Medium', priority_label: 'Monitor', source: 'web_header_audit', status: 'in_progress', owner: 'app-team', due_date: '2026-06-30', updated_at: '2026-05-29T09:10:00+00:00', note: 'Policy draft under review.' },
  { finding_key: 'DEMOFINDING002', title: 'SMB Service Exposed', target: 'demo-windows.local', severity: 'Medium', priority_label: 'Fix Soon', source: 'service_detect', status: 'open', owner: 'infra-team', due_date: '2026-06-20', updated_at: '2026-05-29T09:08:00+00:00', note: 'Network exposure review scheduled.' },
  { finding_key: 'DEMOFINDING001', title: 'Demo Local CVE Match', target: 'demo-linux.local', severity: 'High', priority_label: 'Fix First', source: 'cve_feed', status: 'in_progress', owner: 'security-team', due_date: '2026-06-15', updated_at: '2026-05-29T09:06:00+00:00', note: 'Demo metadata only.' },
  { finding_key: 'DEMOFINDING004', title: 'Cookie Missing HttpOnly Flag', target: 'demo-web.local', severity: 'Medium', priority_label: 'Fix Soon', source: 'web_cookie_audit', status: 'fixed', owner: 'app-team', due_date: '2026-06-10', updated_at: '2026-05-29T09:04:00+00:00', note: 'Marked fixed in demo tracking.' },
]

export const demoRemediationSummary: RemediationSummary = {
  open_count: 3,
  in_progress_count: 2,
  fixed_count: 4,
  accepted_risk_count: 1,
  false_positive_count: 0,
  overdue_count: 0,
  total_count: 10,
}
